[phases.setup]
nixPkgs = ["nodejs_20", "python312Full", "bash", "sqlite", "gcc"]
aptPkgs = ["python3-pip", "python3-requests", "python3-numpy", "python3-pandas", "python3-aiohttp", "python3-bs4", "python3-lxml"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node src/index.js"
