[phases.setup]
nixPkgs = ["nodejs_20", "python311Full", "python311Packages.pip", "python311Packages.requests", "python311Packages.numpy", "python311Packages.pandas", "python311Packages.aiohttp", "python311Packages.beautifulsoup4", "python311Packages.lxml", "bash", "sqlite", "gcc"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node src/index.js"
